### ISSUE TITLE
Update templated documents

### ISSUE THREAD

**Issue by larsks** [operate-first/robozome#7]
This repository was generated from a repository template. There are instructions in the README for what needs to be done to apply all the necessary customizations.

**Comment by tssala23** [comment]
I'm unsure what to put for some of the fields:

name: Robozome
description: ?  Describe onboarding app or just an issue parsing app?
prod-namespace: ?
stage-namespace: ?
image: https://quay.io/repository/operate-first/robozome
team: Operate-First
org-repo: https://github.com/operate-first

**Comment by larsks** [comment]
@tumido is this file parsed by any tooling or is it just informational?
